services:
    db:
        image: postgres:17.4-alpine
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - rails-data:/var/lib/postgresql/data

    app: 
        build: .
        container_name: academy_quest_app
        command: bundle exec rails s
        environment:
          SECRET_KEY_BASE: ${SECRET_KEY_BASE}
          DATABASE_URL: ${DATABASE_URL_PRODUCTION}
        volumes:
          - .:/app
        ports:
          - 3000:3000 

volumes:
    rails-data: